---
version: '2'
linters:
  enable:
    - misspell

formatters:
  enable:
    - gci
    - gofumpt
  settings:
    gci:
      sections:
        - standard
        - default
        - prefix(github.com/kumahq)
    
run:
  timeout: 5m
