name: auto-merge
on:
  pull_request:
    types: [labeled,opened,reopened]
    branches:
      - 'master'
      - 'release-*'

jobs:
  pr-mgmt:
    uses: kumahq/.github/.github/workflows/wfc_pr_management.yml@dcc5a536fe6c9afc101ea552b3c15ffeb26b01e9 # main
    with:
      approve: true
      merge: true
      matchLabel: "ci/auto-merge"
    secrets:
      github-token: ${{ secrets.GITHUB_TOKEN }}
