name: project-lifecycle
on:
  schedule:
    - cron: 0 8 * * *
  workflow_dispatch:
  issues:
    types:
      - reopened
      - opened
      - labeled

jobs:
  lifecycle:
    uses: kumahq/.github/.github/workflows/wfc_lifecycle.yml@f8b89ff1817720691612fa145c5154f94585f344 # main
