name: project-lifecycle
on:
  schedule:
    - cron: 0 8 * * *
  workflow_dispatch:
  issues:
    types:
      - reopened
      - opened
      - labeled

jobs:
  lifecycle:
    uses: kumahq/.github/.github/workflows/wfc_lifecycle.yml@dcc5a536fe6c9afc101ea552b3c15ffeb26b01e9 # main
